# Generated by Django 4.1.3 on 2022-11-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quant', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('categ', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='casa',
        ),
    ]
