# Generated by Django 4.1.3 on 2022-11-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='card',
            field=models.CharField(default=123, max_length=3),
            preserve_default=False,
        ),
    ]
